apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "app.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}

    spec:
      containers:
        - name: {{ .Chart.Name }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          resources:
{{ toYaml .Values.resources | indent 12 }}

          env:
{{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
{{- end }}